/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emmastewartgui;

/**
 *
 * @author Emma
 */
public class frmComplete extends javax.swing.JPanel {

    /**
     * Creates new form frmComplete
     */
    public frmComplete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWrktComp = new javax.swing.JLabel();
        lblTotalTime = new javax.swing.JLabel();
        lblTotalDis = new javax.swing.JLabel();
        lblTotalMeters = new javax.swing.JLabel();
        lblSetTime = new javax.swing.JLabel();
        lblMins = new javax.swing.JLabel();
        lblMeters = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        lblWrktComp.setText("Workout completed!");

        lblTotalTime.setText("Total time: ");

        lblTotalDis.setText("Total distance: ");

        lblTotalMeters.setText("5.5");

        lblSetTime.setText("01:30 ");

        lblMins.setText("mins");

        lblMeters.setText("km");

        jButton1.setText("Exit workout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblWrktComp, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblTotalTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSetTime)
                .addGap(9, 9, 9)
                .addComponent(lblMins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTotalDis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMeters, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblWrktComp, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalTime)
                    .addComponent(lblTotalDis)
                    .addComponent(lblTotalMeters)
                    .addComponent(lblSetTime)
                    .addComponent(lblMins)
                    .addComponent(lblMeters))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblMeters;
    private javax.swing.JLabel lblMins;
    private javax.swing.JLabel lblSetTime;
    private javax.swing.JLabel lblTotalDis;
    private javax.swing.JLabel lblTotalMeters;
    private javax.swing.JLabel lblTotalTime;
    private javax.swing.JLabel lblWrktComp;
    // End of variables declaration//GEN-END:variables
}
